# Generated by Django 4.0 on 2021-12-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20211215_2223'),
        ('portfolio', '0002_post_slug'),
    ]

    operations = [
    ]
